; Inno Setup script for Vito.
;
; Built by packaging/build-installer.ps1, which passes the version in:
;   iscc /DAppVersion=2026.7 packaging\vito.iss
;
; Design notes
; ------------
; * Per-user install (PrivilegesRequired=lowest, into {localappdata}\Programs).
;   No UAC prompt, which is what makes an unattended update actually unattended:
;   a per-machine install would ask for elevation every time.
; * Settings, history and recordings live in %APPDATA%\vito and %LOCALAPPDATA%\vito,
;   outside the install directory, so an upgrade never touches them and an
;   uninstall only removes them if you say so.
; * A running Vito holds its own .exe open, so PrepareToInstall asks it to quit
;   first — gracefully, via its own API, rather than killing the process.

#ifndef AppVersion
  #define AppVersion "0.0.0-dev"
#endif
; Windows' own version resource has to be four numbers, which "2026.7" is not —
; the build script passes the padded form alongside the one people read.
#ifndef VerInfo
  #define VerInfo "0.0.0.0"
#endif

#define AppName "Vito"
; The shortcut that launches the background daemon/tray is named separately, so
; it is clearly distinct from the "Open the Vito interface" shortcut and the
; installed-as-app PWA — all three would otherwise read simply "Vito".
#define AppTrayName "Vito Tray"
#define AppPublisher "Vincent Blok"
#define AppURL "https://github.com/vinceecniv/vito"
#define AppExe "vito.exe"

[Setup]
; Never change AppId: it is what ties an update to the existing installation.
AppId={{7E4D2C6A-1F3B-4A58-9C0E-6B2D8F1A5C93}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
VersionInfoVersion={#VerInfo}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
AppUpdatesURL={#AppURL}/releases
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
DisableProgramGroupPage=yes
DisableDirPage=auto
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=..\dist
OutputBaseFilename=Vito-Setup-{#AppVersion}
SetupIconFile=vito.ico
UninstallDisplayIcon={app}\{#AppExe}
UninstallDisplayName={#AppName}
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
; Vito-branded wizard art (generated by packaging/mkwizard.py): the coral→violet
; gradient panel with the mark and wordmark on the Welcome/Finished pages, and the
; mark alone top-right on the inner pages.
WizardImageFile=wizard-large.bmp
WizardSmallImageFile=wizard-small.bmp
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
; Shown on the welcome page; keep it short, the wizard is narrow.
AppComments=Voice In, Text Out
CloseApplications=no
RestartApplications=no

[Languages]
; English first: it is the fallback for any CustomMessage a language lacks.
Name: "en"; MessagesFile: "compiler:Default.isl"
Name: "nl"; MessagesFile: "compiler:Languages\Dutch.isl"
Name: "de"; MessagesFile: "compiler:Languages\German.isl"
Name: "fr"; MessagesFile: "compiler:Languages\French.isl"
Name: "es"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "it"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "pt"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "pl"; MessagesFile: "compiler:Languages\Polish.isl"
Name: "ru"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "ja"; MessagesFile: "compiler:Languages\Japanese.isl"

[CustomMessages]
en.AppTagline=Voice In, Text Out — press a hotkey, speak, and your words are pasted as clean text.
en.TaskDesktop=Create a &desktop shortcut
en.TaskAutostart=Start Vito automatically when I sign in
en.RunVito=Start Vito now
en.OpenUI=Open the Vito interface
en.QuitFailed=Vito is running and could not be closed automatically. Please quit it from the tray icon and try again.
en.RemoveDataDesc=Vito keeps your settings, dictionary, history and recordings in your user profile.%n%nDelete them as well?

nl.AppTagline=Voice In, Text Out — druk een sneltoets, spreek, en je woorden worden als schone tekst geplakt.
nl.TaskDesktop=Snelkoppeling op het &bureaublad maken
nl.TaskAutostart=Vito automatisch starten als ik me aanmeld
nl.RunVito=Vito nu starten
nl.OpenUI=De Vito-interface openen
nl.QuitFailed=Vito draait nog en kon niet automatisch worden afgesloten. Sluit hem af via het systeemvak-icoon en probeer het opnieuw.
nl.RemoveDataDesc=Vito bewaart je instellingen, woordenboek, geschiedenis en opnames in je gebruikersprofiel.%n%nDeze ook verwijderen?

de.AppTagline=Voice In, Text Out — Tastenkürzel drücken, sprechen, und der saubere Text wird eingefügt.
de.TaskDesktop=&Desktop-Verknüpfung erstellen
de.TaskAutostart=Vito bei der Anmeldung automatisch starten
de.RunVito=Vito jetzt starten
de.OpenUI=Vito-Oberfläche öffnen
de.QuitFailed=Vito läuft und konnte nicht automatisch beendet werden. Bitte über das Infobereich-Symbol beenden und erneut versuchen.
de.RemoveDataDesc=Vito speichert Einstellungen, Wörterbuch, Verlauf und Aufnahmen in Ihrem Benutzerprofil.%n%nSollen diese ebenfalls gelöscht werden?

fr.AppTagline=Voice In, Text Out — appuyez sur un raccourci, parlez, et votre texte est collé au propre.
fr.TaskDesktop=Créer un raccourci sur le &Bureau
fr.TaskAutostart=Lancer Vito automatiquement à l'ouverture de session
fr.RunVito=Lancer Vito maintenant
fr.OpenUI=Ouvrir l'interface de Vito
fr.QuitFailed=Vito est en cours d'exécution et n'a pas pu être fermé automatiquement. Quittez-le depuis l'icône de la zone de notification, puis réessayez.
fr.RemoveDataDesc=Vito conserve vos réglages, votre dictionnaire, votre historique et vos enregistrements dans votre profil utilisateur.%n%nLes supprimer également ?

es.AppTagline=Voice In, Text Out — pulsa un atajo, habla, y tu texto se pega ya limpio.
es.TaskDesktop=Crear un acceso directo en el &escritorio
es.TaskAutostart=Iniciar Vito automáticamente al iniciar sesión
es.RunVito=Iniciar Vito ahora
es.OpenUI=Abrir la interfaz de Vito
es.QuitFailed=Vito está en ejecución y no se pudo cerrar automáticamente. Ciérralo desde el icono del área de notificación e inténtalo de nuevo.
es.RemoveDataDesc=Vito guarda tus ajustes, diccionario, historial y grabaciones en tu perfil de usuario.%n%n¿Eliminarlos también?

it.AppTagline=Voice In, Text Out — premi una scorciatoia, parla, e il testo pulito viene incollato.
it.TaskDesktop=Crea un collegamento sul &desktop
it.TaskAutostart=Avvia Vito automaticamente all'accesso
it.RunVito=Avvia Vito adesso
it.OpenUI=Apri l'interfaccia di Vito
it.QuitFailed=Vito è in esecuzione e non è stato possibile chiuderlo automaticamente. Chiudilo dall'icona nell'area di notifica e riprova.
it.RemoveDataDesc=Vito conserva impostazioni, dizionario, cronologia e registrazioni nel tuo profilo utente.%n%nEliminarli anche?

pt.AppTagline=Voice In, Text Out — prima um atalho, fale, e o texto é colado já limpo.
pt.TaskDesktop=Criar um atalho no &ambiente de trabalho
pt.TaskAutostart=Iniciar o Vito automaticamente ao iniciar sessão
pt.RunVito=Iniciar o Vito agora
pt.OpenUI=Abrir a interface do Vito
pt.QuitFailed=O Vito está em execução e não foi possível fechá-lo automaticamente. Feche-o pelo ícone da área de notificação e tente novamente.
pt.RemoveDataDesc=O Vito guarda as suas definições, dicionário, histórico e gravações no seu perfil de utilizador.%n%nEliminar também?

pl.AppTagline=Voice In, Text Out — naciśnij skrót, mów, a gotowy tekst zostanie wklejony.
pl.TaskDesktop=Utwórz skrót na &pulpicie
pl.TaskAutostart=Uruchamiaj Vito automatycznie po zalogowaniu
pl.RunVito=Uruchom Vito teraz
pl.OpenUI=Otwórz interfejs Vito
pl.QuitFailed=Vito jest uruchomiony i nie udało się go zamknąć automatycznie. Zamknij go z ikony w zasobniku systemowym i spróbuj ponownie.
pl.RemoveDataDesc=Vito przechowuje ustawienia, słownik, historię i nagrania w Twoim profilu użytkownika.%n%nUsunąć je również?

ru.AppTagline=Voice In, Text Out — нажмите сочетание клавиш, говорите, и готовый текст будет вставлен.
ru.TaskDesktop=Создать ярлык на &рабочем столе
ru.TaskAutostart=Запускать Vito автоматически при входе в систему
ru.RunVito=Запустить Vito сейчас
ru.OpenUI=Открыть интерфейс Vito
ru.QuitFailed=Vito запущен и не удалось закрыть его автоматически. Закройте его через значок в области уведомлений и повторите попытку.
ru.RemoveDataDesc=Vito хранит настройки, словарь, историю и записи в вашем профиле пользователя.%n%nУдалить их тоже?

ja.AppTagline=Voice In, Text Out — ショートカットキーを押して話すと、整えられたテキストが貼り付けられます。
ja.TaskDesktop=デスクトップにショートカットを作成する(&D)
ja.TaskAutostart=サインイン時に Vito を自動的に起動する
ja.RunVito=Vito を今すぐ起動する
ja.OpenUI=Vito のインターフェイスを開く
ja.QuitFailed=Vito が実行中で、自動的に終了できませんでした。通知領域のアイコンから終了して、もう一度お試しください。
ja.RemoveDataDesc=Vito は設定・辞書・履歴・録音をユーザープロファイルに保存しています。%n%nこれらも削除しますか？

[Tasks]
Name: "desktopicon"; Description: "{cm:TaskDesktop}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "autostart";   Description: "{cm:TaskAutostart}"

[Files]
Source: "..\dist\{#AppExe}"; DestDir: "{app}"; Flags: ignoreversion
Source: "vito.ico";          DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#AppTrayName}";                Filename: "{app}\{#AppExe}"; Parameters: "serve"; IconFilename: "{app}\vito.ico"; Comment: "{cm:AppTagline}"
Name: "{group}\{cm:OpenUI}";                   Filename: "http://127.0.0.1:4573/"; IconFilename: "{app}\vito.ico"
Name: "{autodesktop}\{#AppTrayName}";          Filename: "{app}\{#AppExe}"; Parameters: "serve"; IconFilename: "{app}\vito.ico"; Tasks: desktopicon

[Run]
; Autostart is the app's own business — it rewrites the login-startup entry at
; every start so it always points at itself. Rather than seed a raw registry
; value here (which risks differing, byte for byte, from what the app writes and
; then failing to launch), we let Vito set it through its own code path. Runs
; before `serve` so the daemon's self-repair already sees it enabled.
Filename: "{app}\{#AppExe}"; Parameters: "autostart on"; Flags: runhidden; Tasks: autostart
; No skipifsilent here: an unattended update must bring Vito back up by itself.
Filename: "{app}\{#AppExe}"; Parameters: "serve"; Description: "{cm:RunVito}"; Flags: nowait postinstall
Filename: "http://127.0.0.1:4573/"; Description: "{cm:OpenUI}"; Flags: shellexec nowait postinstall skipifsilent

[UninstallRun]
; Stop the daemon before its files disappear underneath it.
Filename: "{app}\{#AppExe}"; Parameters: "quit"; Flags: runhidden; RunOnceId: "QuitVito"
; Remove the login-startup entry through the app itself (mirrors "autostart on"),
; so nothing is left pointing at the deleted executable.
Filename: "{app}\{#AppExe}"; Parameters: "autostart off"; Flags: runhidden; RunOnceId: "AutostartOff"

[Code]
function VitoRunning(): Boolean;
var
  ResultCode: Integer;
begin
  // `vito status` returns a non-zero exit code when nothing answers the port.
  Result := Exec(ExpandConstant('{app}\{#AppExe}'), 'status', '', SW_HIDE,
                 ewWaitUntilTerminated, ResultCode) and (ResultCode = 0);
end;

// PrepareToInstall runs before any file is replaced. Only an already-installed
// Vito is asked to quit — a copy running from somewhere else (a development
// build, say) is none of the installer's business.
function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  ResultCode, WaitedMs: Integer;
begin
  Result := '';
  if not FileExists(ExpandConstant('{app}\{#AppExe}')) then
    Exit;
  if not VitoRunning() then
    Exit;

  Exec(ExpandConstant('{app}\{#AppExe}'), 'quit', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  WaitedMs := 0;
  while (WaitedMs < 8000) and VitoRunning() do
  begin
    Sleep(250);
    WaitedMs := WaitedMs + 250;
  end;
  if VitoRunning() then
    Result := CustomMessage('QuitFailed');
end;

// On uninstall, ask before removing anything of the user's own. Silent
// uninstalls take the default, which is to keep it: losing your API keys,
// dictionary and history to an unattended update would be unforgivable.
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
begin
  if CurUninstallStep <> usPostUninstall then
    Exit;
  if SuppressibleMsgBox(CustomMessage('RemoveDataDesc'), mbConfirmation,
                        MB_YESNO or MB_DEFBUTTON2, IDNO) = IDYES then
  begin
    DelTree(ExpandConstant('{userappdata}\vito'), True, True, True);
    DelTree(ExpandConstant('{localappdata}\vito'), True, True, True);
  end;
end;
